const BLOCKED_SHOT = 'BLOCKED_SHOT';
const SHOT = 'SHOT';
const GOAL = 'GOAL';
const MISSED_SHOT = 'MISSED_SHOT';
const PERIOD_END = 'PERIOD_END';
const CHALLENGE = 'CHALLENGE';
const STOP = 'STOP';
const PENALTY = 'PENALTY';

export { BLOCKED_SHOT, SHOT, GOAL, MISSED_SHOT, PERIOD_END, CHALLENGE, PENALTY, STOP }